const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const key =
  process.env.SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  '';
const gaId =
  process.env.GA_MEASUREMENT_ID ||
  process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID ||
  process.env.GOOGLE_ANALYTICS_ID ||
  '';

const out = path.join(__dirname, '..', 'config.js');

// Keep local placeholder config when env vars are missing (local `npm run build`)
if (!url || !key) {
  console.log('[build] No SUPABASE_URL / SUPABASE_ANON_KEY — leaving config.js unchanged');
  if (!fs.existsSync(out)) {
    fs.copyFileSync(path.join(__dirname, '..', 'config.example.js'), out);
  }
  process.exit(0);
}

const contents = `/* Auto-generated by scripts/write-config.js — do not edit on Vercel */
window.SUPABASE_URL = ${JSON.stringify(url)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(key)};
window.GA_MEASUREMENT_ID = ${JSON.stringify(gaId)};
`;

fs.writeFileSync(out, contents, 'utf8');
console.log('[build] Wrote config.js from environment variables');
